name: Generate Snake

on:
  schedule:
    # Her 6 saatte bir çalıştır
    - cron: "0 */6 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3  # Node.js 20 uyumlu sürüm

      - name: Generate Snake
        uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: Batuhanemregk
          gif_out_path: dist/github-contribution-grid-snake.gif
          svg_out_path: dist/github-contribution-grid-snake.svg

      - name: Show Git Status
        run: git status

      - name: Configure Git
        run: |
          git config user.name "your-username"
          git config user.email "your-email@example.com"

      - name: Push Changes
        uses: ad-m/github-push-action@v0.6.0  # Versiyonu belirledik
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: master
          force: true

      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v3  # Node.js 20 uyumlu sürüm
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
