name: Generate Snake2

on:
  schedule:
    # Her 6 saatte bir çalıştır
    - cron: "0 */6 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3  # Node.js 20 uyumlu sürüm

      - name: Generate Snake
        uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: Batuhanemregk
          gif_out_path: dist/github-contribution-grid-snake.gif
          svg_out_path: dist/github-contribution-grid-snake.svg

      - name: Configure Git
        run: |
          git config --global user.name "Batuhanemregk"
          git config --global user.email "batuhan_e_g@hotmail.com"

      - name: Commit and Push Changes
        run: |
          git add dist/github-contribution-grid-snake.gif dist/github-contribution-grid-snake.svg
          git commit -m "Update snake animation"
          git push origin HEAD:master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v3  # Node.js 20 uyumlu sürüm
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
